### ISSUE TITLE
Somme de String

### ISSUE THREAD

**Issue by Cieldara** [WaffleBuffer/Koalas#1]
Vous voulez vraiment garder cette option ? Je trouve que ça n'apporte pas grand chose et ça me complexifie pas mal la tâche pour le Group By.

Dans la version actuelle, le Group By ne marche pas, j'ai corrigé et permis de faire avec plusieurs colonnes, je push ça bientôt !

**Comment by WaffleBuffer** [comment]
À la base, l'intérêt de cette bibliothèque est de pouvoir facilement réaliser des opérations sur de nombreuses données de types différentes. Après, il vaut mieux commencé par avoir un petit bout qui fonctionne et éventuellement l'améliorer. Donc si ça t'embête vraiment, ne le fait pas.
